name: Generate wiki from code

on:
  push:
    branches: 
      - master

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync Wiki
        uses: joeizzard/action-wiki-sync@v1
        with:
          username: SciLor
          access_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          wiki_folder: wiki
          commit_username: 'Wiki-Action'
          commit_email: 'scilor@users.noreply.github.com'
          commit_message: 'Automatically publish wiki'
